
CREATE PROCEDURE PASO_A_PASO.keys
as


ALTER TABLE PASO_A_PASO.Usuario ADD CONSTRAINT PK_Usuario PRIMARY KEY (user_id);
ALTER TABLE PASO_A_PASO.Cliente ADD CONSTRAINT PK_Cliente PRIMARY KEY (clie_id);
ALTER TABLE PASO_A_PASO.Proveedor ADD CONSTRAINT PK_Proveedor PRIMARY KEY (prov_id);
ALTER TABLE PASO_A_PASO.Rubro ADD CONSTRAINT PK_Rubro  PRIMARY KEY (rubr_id);
ALTER TABLE PASO_A_PASO.Rol ADD CONSTRAINT PK_Rol PRIMARY KEY (rol_id);
ALTER TABLE PASO_A_PASO.RolxUsuario ADD CONSTRAINT PK_RolxUsuario PRIMARY KEY (id_rol,id_usuario);
ALTER TABLE PASO_A_PASO.Funcion ADD CONSTRAINT PK_Funcion PRIMARY KEY (func_id);
ALTER TABLE PASO_A_PASO.FuncionesxRol ADD CONSTRAINT PK_FuncionesxRol PRIMARY KEY (id_rol,id_funcion);
ALTER TABLE PASO_A_PASO.Credito ADD CONSTRAINT PK_Credito PRIMARY KEY (cred_id);
ALTER TABLE PASO_A_PASO.Cupon ADD CONSTRAINT PK_Cupon PRIMARY KEY (cupo_id);
ALTER TABLE PASO_A_PASO.Compra ADD CONSTRAINT PK_Compra PRIMARY KEY (comp_id);
ALTER TABLE PASO_A_PASO.Factura ADD CONSTRAINT PK_Factura PRIMARY KEY (fact_id);
ALTER TABLE PASO_A_PASO.Oferta ADD CONSTRAINT PK_Oferta PRIMARY KEY (ofer_id);



ALTER TABLE PASO_A_PASO.Cliente ADD CONSTRAINT FK_Cliente_Usuario FOREIGN KEY (clie_userId) REFERENCES PASO_A_PASO.Usuario(user_id);
ALTER TABLE PASO_A_PASO.Proveedor ADD CONSTRAINT FK_Proveedor_Usuario FOREIGN KEY (prov_userId) REFERENCES PASO_A_PASO.Usuario(user_id);
ALTER TABLE PASO_A_PASO.Proveedor ADD CONSTRAINT FK_Proveedor_Rubro FOREIGN KEY (prov_rubro) REFERENCES PASO_A_PASO.Rubro(rubr_id);
ALTER TABLE PASO_A_PASO.RolxUsuario ADD CONSTRAINT FK_RolxUsuario_Usuario FOREIGN KEY (id_usuario) REFERENCES PASO_A_PASO.Usuario(user_id);
ALTER TABLE PASO_A_PASO.RolxUsuario ADD CONSTRAINT FK_RolxUsuario_Rol FOREIGN KEY (id_rol) REFERENCES PASO_A_PASO.Rol(rol_id);
ALTER TABLE PASO_A_PASO.FuncionesxRol ADD CONSTRAINT FK_FuncionesxRol_Funcion FOREIGN KEY (id_funcion) REFERENCES PASO_A_PASO.Funcion(func_id);
ALTER TABLE PASO_A_PASO.FuncionesxRol ADD CONSTRAINT FK_FuncionesxRol_Rol FOREIGN KEY (id_rol) REFERENCES PASO_A_PASO.Rol(rol_id);
ALTER TABLE PASO_A_PASO.Credito ADD CONSTRAINT FK_Credito_Cliente FOREIGN KEY (cred_cliente) REFERENCES PASO_A_PASO.Cliente(clie_id); 
ALTER TABLE PASO_A_PASO.Cupon ADD CONSTRAINT FK_Cupon_Cliente FOREIGN KEY (cupo_cliente) REFERENCES PASO_A_PASO.Cliente(clie_id);
ALTER TABLE PASO_A_PASO.Cupon ADD CONSTRAINT FK_Cupon_Oferta FOREIGN KEY (cupo_oferta) REFERENCES PASO_A_PASO.Oferta(ofer_id);
ALTER TABLE PASO_A_PASO.Cupon ADD CONSTRAINT FK_Cupon_Compra FOREIGN KEY (cupo_compra) REFERENCES PASO_A_PASO.Compra(comp_id);
ALTER TABLE PASO_A_PASO.Compra ADD CONSTRAINT FK_Compra_Factura FOREIGN KEY (comp_factura) REFERENCES PASO_A_PASO.Factura(fact_id);
ALTER TABLE PASO_A_PASO.Compra ADD CONSTRAINT FK_Compra_Cliente FOREIGN KEY (comp_cliente) REFERENCES PASO_A_PASO.Cliente(clie_id);
ALTER TABLE PASO_A_PASO.Compra ADD CONSTRAINT FK_Compra_Oferta FOREIGN KEY (comp_oferta) REFERENCES PASO_A_PASO.Oferta(ofer_id);
ALTER TABLE PASO_A_PASO.Factura ADD CONSTRAINT FK_Factura_Proveedor FOREIGN KEY (fact_proveedor) REFERENCES PASO_A_PASO.Proveedor(prov_id);
ALTER TABLE PASO_A_PASO.Oferta ADD CONSTRAINT FK_Oferta_Proveedor FOREIGN KEY (ofer_proveedor) REFERENCES PASO_A_PASO.Proveedor(prov_id);