CREATE PROCEDURE PASO_A_PASO.BorrarBase
AS
	DROP TABLE PASO_A_PASO.FuncionesxRol
	DROP TABLE PASO_A_PASO.Funcion
	DROP TABLE PASO_A_PASO.RolxUsuario
	DROP TABLE PASO_A_PASO.Rol
	DROP TABLE PASO_A_PASO.Cupon
	DROP TABLE PASO_A_PASO.Compra
	DROP TABLE PASO_A_PASO.Factura
	DROP TABLE PASO_A_PASO.Oferta
	DROP TABLE PASO_A_PASO.Proveedor
	DROP TABLE PASO_A_PASO.Rubro
	DROP TABLE PASO_A_PASO.Credito
	DROP TABLE PASO_A_PASO.Cliente
	DROP TABLE PASO_A_PASO.Usuario
	DROP TABLE PASO_A_PASO.TipoPago

	DROP PROC PASO_A_PASO.inicializacion_tablas
	DROP PROC PASO_A_PASO.creacionTablas
	DROP PROC PASO_A_PASO.keys
	DROP PROC PASO_A_PASO.migracionTablas



