CREATE PROCEDURE PASO_A_PASO.BorrarBase
AS
	DROP TABLE PASO_A_PASO.FuncionesxRol
	DROP TABLE PASO_A_PASO.Funcion
	DROP TABLE PASO_A_PASO.RolxUsuario
	DROP TABLE PASO_A_PASO.Rol
	DROP TABLE PASO_A_PASO.Cupon
	DROP TABLE PASO_A_PASO.Compra
	DROP TABLE PASO_A_PASO.Factura
	DROP TABLE PASO_A_PASO.Oferta
	DROP TABLE PASO_A_PASO.Proveedor
	DROP TABLE PASO_A_PASO.Rubro
	DROP TABLE PASO_A_PASO.Credito
	DROP TABLE PASO_A_PASO.Cliente
	DROP TABLE PASO_A_PASO.Usuario
	DROP TABLE PASO_A_PASO.TipoPago

	DROP PROC PASO_A_PASO.inicializacion_tablas
	DROP PROC PASO_A_PASO.creacionTablas
	DROP PROC PASO_A_PASO.keys
	DROP PROC PASO_A_PASO.migracionTablas
	DROP PROC PASO_A_PASO.cargarCredito
	DROP PROC PASO_A_PASO.crearUsuario
	DROP PROC PASO_A_PASO.generarCompra
	DROP PROC PASO_A_PASO.regalarCupon
	DROP PROC PASO_A_PASO.crearCliente
	DROP PROC PASO_A_PASO.crearOferta
	DROP PROC PASO_A_PASO.crearProveedor
	DROP PROC PASO_A_PASO.deshabilitarRol
	DROP PROC PASO_A_PASO.habilitarRol
	DROP PROC PASO_A_PASO.modificarRol

	DROP FUNCTION PASO_A_PASO.saldoUsuario
	DROP FUNCTION PASO_A_PASO.traerClienteSegunUsuario
	DROP FUNCTION PASO_A_PASO.traerCuponesPropios
	DROP FUNCTION PASO_A_PASO.traerOfertasDisponibles
	
	DROP FUNCTION PASO_A_PASO.busquedaRol_Id
	DROP FUNCTION PASO_A_PASO.busquedaRol_IdYFuncion
	DROP FUNCTION PASO_A_PASO.busquedaRol_IdYNombre
	DROP FUNCTION PASO_A_PASO.busquedaRol_Nombre
	DROP FUNCTION PASO_A_PASO.busquedaRol_Todo
	DROP FUNCTION PASO_A_PASO.busquedarRol_NombreYFuncion
	DROP FUNCTION PASO_A_PASO.logInUsuario
	DROP FUNCTION PASO_A_PASO.proveedor_mayorDescuento
	DROP FUNCTION PASO_A_PASO.prueba
	DROP FUNCTION PASO_A_PASO.traerFunciones
	DROP FUNCTION PASO_A_PASO.traerRoles
	DROP PROCEDURE PASO_A_PASO.crearRol
	
	DROP PROC PASO_A_PASO.BorrarBase




