//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class ArchivoConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static ArchivoConfig defaultInstance = ((ArchivoConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ArchivoConfig())));
        
        public static ArchivoConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-10-14")]
        public global::System.DateTime Fecha {
            get {
                return ((global::System.DateTime)(this["Fecha"]));
            }
        }
    }
}
